name: wind-tft
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.2
  - pip:
      - torch>=2.0.0
      - pytorch-lightning>=2.0.0
      - tensorboard>=2.13.0
      - optuna>=3.1.0
      - pytorch-forecasting>=1.0.0