attention_head_size: 1
categorical_groups: {}
causal_attention: true
dataset_parameters:
  add_encoder_length: false
  add_relative_time_idx: false
  add_target_scales: false
  allow_missing_timesteps: true
  categorical_encoders:
    __group_id__group: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: false
      classes_:
        ? !!python/object/apply:numpy._core.multiarray.scalar
        - &id001 !!python/object/apply:numpy.dtype
          args:
          - i8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - !!binary |
          AAAAAAAAAAA=
        : 0
      classes_vector_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - &id002 !!python/name:numpy.ndarray ''
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id001
        - false
        - !!binary |
          AAAAAAAAAAA=
      warn: true
  constant_fill_strategy: null
  group_ids:
  - group
  lags: null
  max_encoder_length: 168
  max_prediction_length: 48
  min_encoder_length: 168
  min_prediction_idx: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    AAAAAAAAAAA=
  min_prediction_length: 48
  predict_mode: false
  randomize_length: null
  scalers:
    U10: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.7.1
      copy: true
      feature_names_in_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - &id004 !!python/object/apply:numpy.dtype
          args:
          - O8
          - false
          - true
          state: !!python/tuple
          - 3
          - '|'
          - null
          - null
          - null
          - -1
          - -1
          - 63
        - false
        - - U10
      mean_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - &id003 !!python/object/apply:numpy.dtype
          args:
          - f8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - false
        - !!binary |
          orBFnUph3D8=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        gDQAAAAAAAA=
      scale_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          FlZFNHcHwT8=
      var_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          zS3ZyuAfkj8=
      with_mean: true
      with_std: true
    U100: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.7.1
      copy: true
      feature_names_in_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id004
        - false
        - - U100
      mean_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          cNCuL9/j2z8=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        gDQAAAAAAAA=
      scale_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          lhCxjQ77wj8=
      var_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          lzV5F0SElj8=
      with_mean: true
      with_std: true
    V10: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.7.1
      copy: true
      feature_names_in_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id004
        - false
        - - V10
      mean_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          re0V6HI+4D8=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        gDQAAAAAAAA=
      scale_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          w+9SpAq+wj8=
      var_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          NGGALmn0lT8=
      with_mean: true
      with_std: true
    V100: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.7.1
      copy: true
      feature_names_in_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id004
        - false
        - - V100
      mean_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          ykShLIY44D8=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        gDQAAAAAAAA=
      scale_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          NDlBgu9AxT8=
      var_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          c4f+P3w7nD8=
      with_mean: true
      with_std: true
  static_categoricals: null
  static_reals: null
  target: TARGETVAR
  target_normalizer: &id005 !!python/object:pytorch_forecasting.data.encoders.EncoderNormalizer
    _method_kwargs: {}
    center: true
    center_: !!python/object/apply:numpy._core.multiarray.scalar
    - *id003
    - !!binary |
      LmIiyboW0j8=
    max_length: null
    method: standard
    method_kwargs: {}
    scale_: !!python/object/apply:numpy._core.multiarray.scalar
    - *id003
    - !!binary |
      FGOyj5jJ0T8=
    transformation: null
  time_idx: time_idx
  time_varying_known_categoricals: null
  time_varying_known_reals:
  - U10
  - V10
  - U100
  - V100
  time_varying_unknown_categoricals: null
  time_varying_unknown_reals:
  - TARGETVAR
  variable_groups: null
  weight: null
dropout: 0.1
embedding_labels: {}
embedding_paddings: []
embedding_sizes: {}
hidden_continuous_size: 8
hidden_continuous_sizes: {}
hidden_size: 16
learning_rate: 0.03
log_gradient_flow: false
log_interval: 10
log_val_interval: null
lstm_layers: 1
mask_bias: -1000000000.0
max_encoder_length: 168
monotone_constaints: {}
monotone_constraints: {}
optimizer: adam
optimizer_params: null
output_size: 7
output_transformer: *id005
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 4
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals: []
static_reals: []
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder:
- U10
- V10
- U100
- V100
time_varying_reals_encoder:
- U10
- V10
- U100
- V100
- TARGETVAR
weight_decay: 0.0
x_categoricals: []
x_reals:
- U10
- V10
- U100
- V100
- TARGETVAR
